machine:
  environment:
    BUGSNAG_API_KEY: ""
    DEFAULT_URL_OPTIONS_HOST: "example.com"
    EMAIL_DELIVERY_METHOD: "test"
    GOOGLE_ANALYTICS_ID: ""
    INTERCOM_ID: ""
    SECRET_KEY_BASE: "a547405eb83a584cd9dc8e4d351a3614"
    SESSION_SECRET: "2ccea290bcce3461613516b191638831"
    SUPPORT_EMAIL: "hello@sul.im"
