# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b95c395296680ed0a983b600fa810527c92a87cb61570daaebff5978213628af99f0ec6daeefe48f1b1928a26d2dcebe56e26083837cd399fe56a0dd93d034d1

test:
  secret_key_base: 7ad72c67e4f65fe6b4d61f06e4060c6b83d9d9fc29f49037064bd34f98308bbd5a570cbb2abaa504ec6b86fe0f1ab024f3cc1e4634386e9183a7b7b7e1040928

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
